inveniosoftware/invenio-users-resources

- invenio_users_resources/__init__.py
- invenio_users_resources/ext.py
- invenio_users_resources/proxies.py
- invenio_users_resources/resources/__init__.py
- invenio_users_resources/resources/groups/__init__.py
- invenio_users_resources/resources/groups/config.py
- invenio_users_resources/resources/groups/resource.py
- invenio_users_resources/resources/users/__init__.py
- invenio_users_resources/resources/users/config.py
- invenio_users_resources/resources/users/resource.py
- invenio_users_resources/services/__init__.py
- invenio_users_resources/services/common.py
- invenio_users_resources/services/groups/__init__.py
- invenio_users_resources/services/groups/config.py
- invenio_users_resources/services/groups/results.py
- invenio_users_resources/services/groups/service.py
- invenio_users_resources/services/permissions.py
- invenio_users_resources/services/schemas.py
- invenio_users_resources/services/users/__init__.py
- invenio_users_resources/services/users/config.py
- invenio_users_resources/services/users/results.py
- invenio_users_resources/services/users/service.py
- invenio_users_resources/views.py
- setup.py
- tests/conftest.py
- tests/test_invenio_users_resources.py
initial sketches for services and resources
closes #1 
closes #2
> global: initial draft for services and resources

- invenio_users_resources/__init__.py
- invenio_users_resources/ext.py
- invenio_users_resources/records/api.py
- invenio_users_resources/records/mappings/v6/users/user-v1.0.0.json
- invenio_users_resources/records/mappings/v7/users/user-v1.0.0.json
- invenio_users_resources/records/systemfields/__init__.py
- invenio_users_resources/records/systemfields/current_user.py
- invenio_users_resources/services/permissions.py
- invenio_users_resources/services/schemas.py
- invenio_users_resources/services/users/service.py
- invenio_users_resources/utils.py
Adapt the module to the changes made to Invenio-Accounts in https://github.com/inveniosoftware/invenio-accounts/pull/390 (i.e. addition of JSON-based fields for user profile and preferences.
Also, this PR adds a system field that calculates the value for `is_current_user` rather than just giving back `False`.
Edit: the visibility settings were moved into the default preferences schema in Invenio-Accounts.
> Adapt to new Invenio-Accounts features

- .gitignore
- LICENSE
- MANIFEST.in
- docs/conf.py
- invenio_users_resources/__init__.py
- invenio_users_resources/config.py
- invenio_users_resources/ext.py
- invenio_users_resources/records/api.py
- invenio_users_resources/records/systemfields/current_user.py
- invenio_users_resources/resources/groups/config.py
- invenio_users_resources/resources/groups/resource.py
- invenio_users_resources/resources/users/config.py
- invenio_users_resources/resources/users/resource.py
- invenio_users_resources/services/groups/config.py
- invenio_users_resources/services/groups/results.py
- invenio_users_resources/services/groups/service.py
- invenio_users_resources/services/permissions.py
- invenio_users_resources/services/results.py
- invenio_users_resources/services/users/config.py
- invenio_users_resources/services/users/results.py
- invenio_users_resources/services/users/service.py
- invenio_users_resources/templates/avatar.svg
- invenio_users_resources/views.py
- run-tests.sh
- setup.cfg
- tests/conftest.py
- tests/resources/test_avatars.py
Issue #3: User and group avatars:
- API return an svg with the first letter of the name (full_name, username, email- for user, name for group), no caching
- Standard tests for API (plus sgv comparaison)
> Issue #3 avatars

- invenio_users_resources/ext.py
- setup.cfg
**Reminder**
2. You agree that you have the right to license your contribution under the current repository’s license.
> global: remove dependency on invenio-userprofiles

- invenio_users_resources/records/api.py
- invenio_users_resources/records/mappings/v6/groups/group-v1.0.0.json
- invenio_users_resources/records/mappings/v7/groups/group-v1.0.0.json
- invenio_users_resources/records/models.py
- invenio_users_resources/resources/groups/resource.py
- invenio_users_resources/services/groups/config.py
- invenio_users_resources/services/groups/service.py
- tests/resources/test_resources_groups.py
- tests/services/test_service_groups.py
* closes https://github.com/inveniosoftware/invenio-communities/issues/611
> members: remap group model id to role name

- invenio_users_resources/__init__.py
- invenio_users_resources/services/groups/results.py
- invenio_users_resources/services/users/results.py
* constructor should expect additional kwargs
> users: add kwargs to the result item constructor

- invenio_users_resources/__init__.py
- invenio_users_resources/services/groups/tasks.py
- invenio_users_resources/services/users/tasks.py
- requires https://github.com/inveniosoftware/invenio-indexer/pull/139
> tasks: delegate index exist check to indexer

- babel.ini
- invenio_users_resources/translations/messages.pot
* remove jinja extensions
* update .pot
related inveniosoftware/invenio-app-rdm/issues/1664
> i18n: update pot file

- invenio_users_resources/__init__.py
- invenio_users_resources/services/groups/service.py
- invenio_users_resources/services/permissions.py
- tests/resources/test_resources_groups.py
> Groups permissions

- invenio_users_resources/translations/de/LC_MESSAGES/messages.po
* add german translations
related inveniosoftware/invenio-app-rdm/issues/1664
> i18n: add de translations

- CHANGES.rst
- invenio_users_resources/__init__.py
- invenio_users_resources/resolvers.py
- invenio_users_resources/services/groups/results.py
- invenio_users_resources/services/users/results.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1987
> expand: pass identity when picking fields

- invenio_users_resources/records/api.py
- invenio_users_resources/records/mappings/os-v1/users/user-v1.0.0.json
- invenio_users_resources/records/mappings/os-v2/users/user-v1.0.0.json
- invenio_users_resources/records/mappings/v7/users/user-v1.0.0.json
- invenio_users_resources/services/schemas.py
- tests/resources/test_resources_users.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2069
> preferences: add support for preferences.locale

- MANIFEST.in
- invenio_users_resources/forms.py
- invenio_users_resources/models.py
- invenio_users_resources/templates/semantic-ui/invenio_users_resources/settings/notifications.html
ui: add notification settings preferences template
closes https://github.com/inveniosoftware/invenio-communities/issues/864
Add a notification settings model, form and handler.
Add UI template for setting section.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repos …
> forms: add notification preferences form and handle

- CHANGES.rst
> release: v2.0.0

- invenio_users_resources/__init__.py
> release-fix: bump version to v2.0.0

- invenio_users_resources/entity_resolvers.py
- invenio_users_resources/services/schemas.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2229
> ui: crash when username is null

- invenio_users_resources/templates/semantic-ui/invenio_users_resources/settings/notifications.html
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2301
> settings notifications: Layout and a11y fixes

- CHANGES.rst
- invenio_users_resources/__init__.py
> release: v2.1.2

- invenio_users_resources/entity_resolvers.py
- invenio_users_resources/permissions.py
- invenio_users_resources/records/api.py
- invenio_users_resources/records/mappings/os-v1/users/user-v1.0.0.json
- invenio_users_resources/records/mappings/os-v2/users/user-v1.0.0.json
- invenio_users_resources/records/mappings/v7/users/user-v1.0.0.json
- invenio_users_resources/records/models.py
- invenio_users_resources/services/generators.py
- invenio_users_resources/services/permissions.py
- invenio_users_resources/services/schemas.py
- invenio_users_resources/services/users/service.py
- setup.cfg
- tests/conftest.py
- tests/services/test_service_users.py
closes https://github.com/inveniosoftware/invenio-users-resources/issues/92
NEEDS:
- https://github.com/inveniosoftware/invenio-accounts/pull/447
- https://github.com/inveniosoftware/invenio-records-permissions/pull/93
> users: added moderation actions

- CHANGES.rst
- invenio_users_resources/__init__.py
> release: v2.2.0

- invenio_users_resources/ext.py
- invenio_users_resources/proxies.py
- invenio_users_resources/records/api.py
- invenio_users_resources/services/permissions.py
- invenio_users_resources/services/users/service.py
- invenio_users_resources/services/users/tasks.py
- tests/services/test_service_users.py
closes https://github.com/inveniosoftware/invenio-users-resources/issues/95
requires: 
- https://github.com/inveniosoftware/invenio-users-resources/pull/91
**For reviewers**
Review only the last PR, the rest are part of the first deliverable.
> moderation: added actions registry

- invenio_users_resources/templates/semantic-ui/invenio_users_resources/settings/notifications.html
Align the template default value with the default value in the [users API](https://github.com/inveniosoftware/invenio-users-resources/blob/112423bc782f3fc8ac7fd7b3f9a07fdda4aa8479/invenio_users_resources/records/api.py#L45C1-L50).
In a later step, a general configuration variable for the default value shall be introduced.
**Reminder**
By using GitHub, you have already agreed to the …
> template: set default value notifications enabled to True

- invenio_users_resources/services/generators.py
- invenio_users_resources/services/permissions.py
- tests/conftest.py
- tests/resources/test_resources_groups.py
- tests/services/test_service_groups.py
depends on https://github.com/inveniosoftware/invenio-records-permissions/pull/95
closes https://github.com/zenodo/rdm-project/issues/215
Add group query filter based on the identity.
Permissions for group `can_read` have been adapted. Authenticated users shall only retrieve groups where `is_managed` is false.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s …
> Filter managed groups

- CHANGES.rst
- invenio_users_resources/__init__.py
> release: v2.5.0

- CHANGES.rst
- invenio_users_resources/__init__.py
> release: v2.6.0

- CHANGES.rst
- invenio_users_resources/__init__.py
> release: v3.0.1

- CHANGES.rst
- invenio_users_resources/__init__.py
> release: v3.0.2

- invenio_users_resources/notifications/filters.py
- invenio_users_resources/notifications/generators.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1454
depends on https://github.com/inveniosoftware/invenio-notifications/pull/23
Introduces email recipient generator and conditional user recipient generator.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributi …
> notifications add email and conditional user recipient generators

- CHANGES.rst
- invenio_users_resources/__init__.py
> release: v3.1.0

- invenio_users_resources/records/api.py
- invenio_users_resources/records/models.py
* closes https://github.com/zenodo/zenodo-rdm/issues/590
> model: prevent flush on select queries

- invenio_users_resources/records/mappings/v7/domains/domain-v1.0.0.json
* To prevent tests in other repositories from failing.
> records: add elasticsearch 7 mapping

- invenio_users_resources/entity_resolvers.py
Pick the fields `id` and `name` after resolving a group.
When expanding a `group` in a request, the expanded object is currently empty. This will return basic information about the group.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including …
> resolvers: pick resolved fields for group

- invenio_users_resources/forms.py
The current notification form text doesn't clearly indicate how the toggle relates to the notification status. This PR makes the text more descriptive and less wordy.
Ideally this text could be set somewhere outside of the .py file, but not sure the best way to architect that.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …
> form: Update form text

- .github/workflows/tests.yml
- invenio_users_resources/resources/groups/config.py
- invenio_users_resources/resources/users/config.py
* closes https://github.com/zenodo/rdm-project/issues/598
> http headers: use and adjust vnd.inveniordm.v1+json http accept header

- .github/workflows/pypi-publish.yml
- .github/workflows/tests.yml
- CHANGES.rst
- invenio_users_resources/__init__.py
- invenio_users_resources/services/users/config.py
- setup.cfg
- setup: bump major dependencies
- setup: change to reusable workflows
- release: v7.0.0.dev1
> bump major

- invenio_users_resources/ext.py
- setup.cfg
Replaced `importlib_metadata` and `importlib_resources` with `importlib`.
* Using invenio_base.utils.entry_points for entry_points
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
2. You agree that you have the …
> chores: replaced importlib_xyz with importlib
