inveniosoftware/invenio-users-resources

invenio_users_resources/ext.py
invenio_users_resources/records/__init__.py
invenio_users_resources/records/api.py
invenio_users_resources/records/jsonschemas/__init__.py
invenio_users_resources/records/jsonschemas/users/group-v1.0.0.json
invenio_users_resources/records/jsonschemas/users/user-v1.0.0.json
invenio_users_resources/records/mappings/__init__.py
invenio_users_resources/records/mappings/v6/__init__.py
invenio_users_resources/records/mappings/v6/user_groups/group-v1.0.0.json
invenio_users_resources/records/mappings/v6/users/user-v1.0.0.json
invenio_users_resources/records/mappings/v7/__init__.py
invenio_users_resources/records/mappings/v7/user_groups/group-v1.0.0.json
invenio_users_resources/records/mappings/v7/users/user-v1.0.0.json
invenio_users_resources/records/models.py
invenio_users_resources/services/groups/config.py
invenio_users_resources/services/groups/results.py
invenio_users_resources/services/groups/service.py
invenio_users_resources/services/permissions.py
invenio_users_resources/services/schemas.py
invenio_users_resources/services/users/config.py
invenio_users_resources/services/users/results.py
invenio_users_resources/services/users/service.py
setup.py

Make the services operate on Elasticsearch indices rather than DB queries.
This requires API classes for UserAggregations, along with mock models (which don't save anything to the database, because this would effectively duplicate information).
Even though they're not saved in DB, these entities still need to be indexed in ES (which needs mappings).
For now, the focus is on "read" operations, as there's other mechanisms to create users and roles.
I've still added a rudimentary "create" operation for users, mainly for testing purposes (a single function that creates and indexes users/aggregations).
This PR primarily lays the foundation for having the services work with Elasticsearch indices (and schemas, etc.) rather than via direct DB look-ups.
The details of the schemas, APIs (especially …

Index-based services

---

invenio_users_resources/ext.py
invenio_users_resources/proxies.py
invenio_users_resources/records/api.py
invenio_users_resources/records/dumpers/__init__.py
invenio_users_resources/records/models.py
invenio_users_resources/services/permissions.py
invenio_users_resources/services/schemas.py
invenio_users_resources/utils.py
setup.py
tests/conftest.py

* use the timestamp and version information from the reworked user model
for indexing purposes
* register ~~mapper~~ session event hooks for keeping the search indices up to date
with the database model
* ~~experimental results seemed to show that the mapper events are only
emitted in the db connection that issued the statements, and thus we
should not have a problem with multiple event handlers firing for the
same event~~
edit: reworked to use session events rather than mapper events because we want to reindex the entities if and only if the DB commit went through; still needs some more testing.

users: use user model version_id and register session event hooks

---

invenio_users_resources/ext.py

- closes #25
- another problem faced was that using set() rather than reyling on the
fact that session.dirty/new already follows the set protocol resulted in
errors when commiting ObjectVersion (from invenio-files-rest) - error
would be thrown about ObjectVersion not being hashable. Using the normal
set protocol of session.dirty/new sidesteps this issue.

remove _model_changes access and fix set usage [+]

---

invenio_users_resources/services/groups/service.py
invenio_users_resources/services/users/service.py

Make the `service.rebuild_index` method use bulk indexing rather than indexing each item individually.
This is related to https://github.com/inveniosoftware/invenio-records-resources/pull/419.
All the relevant requirements were already in place: `UserAggregate.get_record(id)`, and the `index` system field; same for groups.

Bulk indexing for `rebuild_index`

---

CHANGES.rst
invenio_users_resources/__init__.py
invenio_users_resources/services/groups/config.py
invenio_users_resources/services/schemas.py
run-tests.sh
setup.cfg

- migrate: flask_babelex replaced by invenio_i18n
- fix: --dry-run ignored
- NOTE: invenio-accounts invenio-admin invenio-files-rest invenio-i18n invenio-oauthclient invenio-pidstore invenio-records invenio-records-resources invenio-theme have to be released first

migrate to flask babel

---

invenio_users_resources/ext.py
invenio_users_resources/records/api.py
invenio_users_resources/records/hooks.py
invenio_users_resources/records/mappings/os-v1/groups/group-v1.0.0.json
invenio_users_resources/records/mappings/os-v2/groups/group-v1.0.0.json
invenio_users_resources/records/mappings/v7/groups/group-v1.0.0.json
run-tests.sh
setup.cfg
tests/conftest.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2186
* NEEDS https://github.com/inveniosoftware/invenio-access/pull/203
* NEEDS https://github.com/inveniosoftware/invenio-accounts/pull/439

groups: updates mapping to contain description

---

invenio_users_resources/records/hooks.py
invenio_users_resources/services/groups/tasks.py
invenio_users_resources/services/users/tasks.py
tests/conftest.py

* closes https://github.com/inveniosoftware/invenio-users-resources/issues/76

wip: index new groups in OpenSearch

---

.github/workflows/tests.yml
CHANGES.rst
invenio_users_resources/__init__.py
invenio_users_resources/administration/__init__.py
invenio_users_resources/administration/views/__init__.py
invenio_users_resources/administration/views/users.py
invenio_users_resources/config.py
invenio_users_resources/services/users/config.py
setup.cfg

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2232
**Reminder**
1. You license your contribution under the same terms as the …

Draft of the user admin

---

invenio_users_resources/records/api.py
invenio_users_resources/resources/users/config.py
invenio_users_resources/resources/users/resource.py
invenio_users_resources/services/users/service.py
tests/resources/test_resources_users.py
tests/services/test_service_users.py

closes https://github.com/inveniosoftware/invenio-requests/issues/344
We decided to add the endpoints in this deliverable since it was a minor effort for now.

resources: added management endpoints.

---

invenio_users_resources/entity_resolvers.py

Note: The issue is that `user-administration` is not a group that is indexed in ES. Therefore, when expanding the moderation request the group can't be expanded and defaults to `ghost_record`.

resolvers: added ghost record for groups.

---

invenio_users_resources/resources/users/config.py
invenio_users_resources/resources/users/resource.py
invenio_users_resources/services/permissions.py
invenio_users_resources/services/users/service.py
tests/resources/test_resources_users.py

Depends on inveniosoftware/flask-security-fork#60 and inveniosoftware/invenio-accounts#461

resources: add support for user impersonation

---

invenio_users_resources/services/users/lock.py
invenio_users_resources/services/users/service.py

closes https://github.com/zenodo/rdm-project/issues/464

lock: added return statement to lock acquire.

---

invenio_users_resources/records/mappings/os-v1/domains/domain-v1.0.0.json
invenio_users_resources/records/mappings/os-v1/users/user-v1.0.0.json
invenio_users_resources/records/mappings/os-v1/users/user-v2.0.0.json
invenio_users_resources/records/mappings/os-v2/domains/domain-v1.0.0.json
invenio_users_resources/records/mappings/os-v2/users/user-v1.0.0.json
invenio_users_resources/records/mappings/os-v2/users/user-v2.0.0.json
invenio_users_resources/records/mappings/v7/domains/domain-v1.0.0.json
invenio_users_resources/records/mappings/v7/users/user-v1.0.0.json
invenio_users_resources/records/mappings/v7/users/user-v2.0.0.json

- The mapping is stored as a string/enum in ES/OS. Using the same type
makes sure the mapping comparison is correct when performing a
mapping update.

mappings: change "dynamic" values to string

---

invenio_users_resources/config.py
invenio_users_resources/services/generators.py
invenio_users_resources/services/permissions.py
tests/conftest.py

* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1672

permissions: add generator for handling groups enabled feature flag

---

invenio_users_resources/services/users/config.py
tests/resources/test_resources_users.py

* Fix admin user lists show no results from the backend.
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2721
* Closes https://github.com/inveniosoftware/invenio-app-rdm/pull/2722
* Closes https://github.com/inveniosoftware/invenio-administration/issues/201
* No need to change moderation links as they are functional
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
By using GitHub, you have already agreed …

moderation: fix admin record / draft links

---

.github/workflows/tests.yml

* Change branches type from string to array
* Switch to centralised workflows
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
2. You agree that …

CI: Switch To Centralised Workflows

---

.github/workflows/pypi-publish.yml
.github/workflows/tests.yml
CHANGES.rst
invenio_users_resources/__init__.py
setup.cfg

- **setup: bump major dependencies**
- **setup: change to reusable workflows**
- **release: v7.0.0.dev1**
- **📦 release: v7.0.0.dev2**

Flask v3 upgrade

---

invenio_users_resources/services/domains/facets.py
invenio_users_resources/services/users/facets.py

User and domain translations are not working, even though they are wrapped in `_(...)`. The reason is `gettext` is used which performs the translation during module initialization and not when the facets are rendered.
This PR fixes this by using `lazy_gettext` instead.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions- …

i18n: Fix untranslated strings in facets

---

CHANGES.rst
invenio_users_resources/__init__.py
invenio_users_resources/services/schemas.py
tests/conftest.py

* When the entity resolver returns the system user, it doesn't contain the email which is required for audit logs
closes: https://github.com/CERNDocumentServer/cds-rdm/issues/359
related: https://github.com/inveniosoftware/invenio-audit-logs/issues/4

services: schemas: Add email field to system user

---

invenio_users_resources/services/schemas.py

* The 'default' argument to fields is deprecated. Use 'dump_default'
instead.

fix: RemovedInMarshmallow4Warning

---

invenio_users_resources/services/generators.py
invenio_users_resources/services/permissions.py
invenio_users_resources/services/users/service.py
tests/resources/test_resources_users.py

* The problem is that an admin could block his own account. With this change, it is possible to prevent the admin from doing that.
* Prevent self-action for: `block`, `deactivate`, `restore`, `activate`, `impersonate` and `approve`.
* Update tests for self-action prevention
* introduce the PreventSelf generator
* introduce `_check_permission` in users service
* add "PreventSelf" into `can_manage` and `can_impersonate` permission
* closes <https://github.com/inveniosoftware/invenio-administration/issues/203>
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependenc …

moderation: add self-action prevention

---

invenio_users_resources/entity_resolvers.py

This is needed, because in some request types with anonymous/guest users, we might end up storing `{"user": None}` as a reference... This is not ideal, but returning an empty list at least keeps downstream usage of the function type-safe.

fix(entity_resolvers): handle `None` user entity
